💃 Added Customizable Messages :Man:
Nuggies-bot/nuggies-npm pull request #25
Opened 2021-07-12 18:11 UTC by ChopChoP534

read readme uwu

2021-07-12 18:14 UTC, Assassin-1234 commented
nice! thanks for contributing :)

can you please move the baseOptions function to Giveaways class tho?

2021-07-12 18:17 UTC, Assassin-1234 commented
> nice! thanks for contributing :)
> 
> can you please move the baseOptions function to Giveaways class tho?

or just refactor the func name to something more relatable

2021-07-12 18:19 UTC, ChopChoP534 commented
done :)

2021-07-12 18:20 UTC, ChopChoP534 commented
> > nice! thanks for contributing :)
> > can you please move the baseOptions function to Giveaways class tho?
> 
> or just refactor the func name to something more relatable

baseMessages? defaultMessages? messages?
u tell me

2021-07-12 18:21 UTC, Assassin-1234 commented
> > > nice! thanks for contributing :)
> > > can you please move the baseOptions function to Giveaways class tho?
> > 
> > 
> > or just refactor the func name to something more relatable
> 
> baseMessages? defaultMessages? messages?
> u tell me

GiveawayMessages sounds good

2021-07-12 18:22 UTC, Assassin-1234 commented
or wait if its in giveaways class then only messages

2021-07-12 18:23 UTC, Assassin-1234 requested changes
everything looks good just change the func name and leave the conficts, I'll resolve them tomorrow morning

2021-07-12 18:46 UTC, ChopChoP534 reviewed
👍

2021-07-13 02:57 UTC, Assassin-1234 approved these changes

2021-07-13 03:44 UTC, Assassin-1234 approved these changes

2021-07-13 13:11 UTC, pro-gamer007 requested changes
Everything is good except from the previous comment i left on line 56 in src/classes/giveaways.js

2021-07-13 16:41 UTC, pro-gamer007 commented on src/classes/giveaways.js
> +		const msg = await message.guild.channels.cache.get(channel).send(message.client.giveawayMessages.giveaway, {
my bad, didnt see it properly 😳

2021-07-13 16:41 UTC, pro-gamer007 approved these changes

2021-07-13 16:56 UTC, LegItMate approved these changes

2021-07-13 17:13 UTC, merged